apiVersion: apps/v1
kind: Deployment
metadata:
  name: secret-chat
spec:
  replicas: 1
  selector:
    matchLabels:
      app: secret-chat
  template:
    metadata:
      labels:
        app: secret-chat
    spec:
      containers:
        - name: secret-chat
          image: secret-chat:latest
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 3000
          readinessProbe:
            httpGet:
              path: /health
              port: http
          livenessProbe:
            httpGet:
              path: /health
              port: http
          securityContext:
            allowPrivilegeEscalation: false
            runAsNonRoot: true
            capabilities:
              drop: ["ALL"]
---
apiVersion: v1
kind: Service
metadata:
  name: secret-chat
spec:
  selector:
    app: secret-chat
  ports:
    - name: http
      port: 80
      targetPort: http
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: secret-chat
spec:
  tls:
    - secretName: secret-chat-tls
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: secret-chat
                port:
                  name: http
