[package]
name = "tauri-plugin-identity"
version = "1.1.1"
authors = [ "ethos-adamas" ]
description = "Hardware-backed Tacitus identity and device storage"
edition = "2024"
exclude = ["/examples", "/dist-js", "/guest-js", "/node_modules"]
links = "tauri-plugin-identity"

[dependencies]
tauri = { version = "2.11.3", default-features = false }
serde = "1.0"
thiserror = "2"

[build-dependencies]
tauri-plugin = { version = "2.6.3", features = ["build"] }
